import BannerPousadaLeAnge from '@/assets/portfolio/design-web-pousadaleange.jpg';
import BannerAleph from '@/assets/portfolio/design-web-alephsramos.jpg';
import BannerNovaMetalica from '@/assets/portfolio/design-web-novametalica.jpg';
import BannerFast from "@/assets/portfolio/design-web-lojafastsistemasconstrutivos.jpg";
import BannerYago from "@/assets/portfolio/design-web-euyagolopes.jpg";

import LogoPousadaLeAnge from '@/assets/brands/pousada-le-ange.png';
import LogoFastSistemasConstrutivos from '@/assets/brands/pousada-le-ange.png';
import LogoUnityCompany from '@/assets/brands/pousada-le-ange.png';
import LogoNovaMetalica from '@/assets/brands/pousada-le-ange.png';
import LogoFastHomes from '@/assets/brands/pousada-le-ange.png';
import LogoKdea from '@/assets/brands/pousada-le-ange.png';
import SemLogo from '@/assets/brands/pousada-le-ange.png';

export const projects = [
    {
        image: "",
        title: "Programa de Fidelidade",
        slug: "programa-de-fidelidade",
        popupContent: "Novidade",
        siteType: "Aplicações",
        imageCompanyUrl: LogoFastSistemasConstrutivos,
        companyName: "Fast Sistemas Construtivos",
        tecnologias: ["react", "supabase", "n8n", "vite", "sass", "javascript" ],
        stack: [
            {
                "techName": "React",
                "tecnologias": ["React"],
                "color": "#61DAFB"
            },
            {
                "techName": "Javascript",
                "tecnologias": ["Javascript"],
                "color": "#F7DF1E"
            }
        ],
        data: "22/09/2025",
        duration: 120,
        plataform: "Código",
        country: "Brasil",
        description: "Sistema de fidelidade para clientes da fast, sistema totalmente focado em ser automono, o próprio usuário consegue fazer tudo sem depender de ninguém.",
        urlPage: "https://fidelidade.fastsistemasconstrutivos.com.br",
        githubUrl: "https://github.com/alephsramos-dev",
        onDetails: "",
        popupBg: "#ffffff",
        popupBorder: "#00000010",
        popupColor: "#000000",
        siteBg: "#ffffff",
        siteBorder: "#00000010",
        siteColor: "#000000",
    },
    {
        image: "https://mir-s3-cdn-cf.behance.net/projects/404/774954210683221.Y3JvcCwxNDA2LDExMDAsMTcsMA.png",
        title: "Gerenciador de Agência",
        popupContent: "Útil",
        slug: "gerenciador-de-agencia",
        siteType: "Aplicações",
        imageCompanyUrl: LogoUnityCompany,
        companyName: "Unity Company",
        tecnologias: ["react", "javascript", "firebase", "vite", "sass"],
        stack: [
            {
                "techName": "React",
                "tecnologias": ["React"],
                "color": "#61DAFB"
            },
            {
                "techName": "Firebase",
                "tecnologias": ["Firebase"],
                "color": "#FFCA28"
            },
            {
                "techName": "Vite",
                "tecnologias": ["Vite"],
                "color": "#646CFF"
            },
            {
                "techName": "Sass",
                "tecnologias": ["Sass"],
                "color": "#CC6699"
            },
            {
                "techName": "Javascript",
                "tecnologias": ["Javascript"],
                "color": "#F7DF1E"
            }
        ],
        data: "22/09/2025",
        duration: 120,
        plataform: "Código",
        country: "Brasil",
        data: "11/02/2025",
        description: "Gerenciador completo para que o time de marketing consiga ter controle total sobre os projetos, clientes, finanças etc.",
        urlPage: "https://gerenciador.unitycompany.com.br",
        githubUrl: "https://github.com/alephsramos-dev",
        onDetails: "",
        popupBg: "#ffffff",
        popupBorder: "#00000010",
        popupColor: "#000000",
        siteBg: "#ffffff",
        siteBorder: "#00000010",
        siteColor: "#000000",
    },
    {
        image: "",
        title: "Sistema de Pré-vendas",
        popupContent: "Útil",
        slug: "sistema-de-pre-vendas",
        siteType: "Aplicações",
        imageCompanyUrl: LogoUnityCompany,
        companyName: "Unity Company",
        tecnologias: ["javascript", "html", "n8n","css", "sass", "firebase"],
        data: "11/02/2025",
        description: "Gerenciador completo para que o time de marketing consiga ter controle total sobre os projetos, clientes, finanças etc.",
        urlPage: "",
        githubUrl: "https://github.com/alephsramos-dev",
        onDetails: "",
        popupBg: "#ffffff",
        popupBorder: "#00000010",
        popupColor: "#000000",
        siteBg: "#ffffff",
        siteBorder: "#00000010",
        siteColor: "#000000",
    },
    {
        image: "",
        title: "euYagoLopes",
        popupContent: "Tendência",
        slug: "euyagolopes",
        siteType: "Landing Page",
        imageCompanyUrl: SemLogo,
        companyName: "euYagoLopes",
        tecnologias: ["javascript", "html","css"],
        data: "08/04/2025",
        description: "Landing page totalmente focada em conversão, apresentando de forma profissional e trazendo um aspecto de alto valor.",
        urlPage: "https://euyagolopes.com.br",
        githubUrl: "https://github.com/alephsramos-dev",
        onDetails: "",
        popupBg: "#ffffff",
        popupBorder: "#00000010",
        popupColor: "#000000",
        siteBg: "#ffffff",
        siteBorder: "#00000010",
        siteColor: "#000000",
    },
    {
        image: "",
        title: "Pousada Le Ange",
        popupContent: "Mais visto",
        slug: "pousada-le-ange",
        siteType: "Institucional",
        imageCompanyUrl: LogoPousadaLeAnge,
        companyName: "Pousada Le Ange",
        tecnologias: ["react", "firebase", "vite", "sass", "javascript"],
        data: "28/06/2024",
        description: "Uma página única focada em apresentar todas as qualidades das duas unidades da pousada.",
        urlPage: "https://pousadaleange.com.br",
        githubUrl: "https://github.com/alephsramos-dev",
        onDetails: "",
        popupBg: "#ffffff",
        popupBorder: "#00000010",
        popupColor: "#000000",
        siteBg: "#ffffff",
        siteBorder: "#00000010",
        siteColor: "#000000",
    },
    {
        image: "",
        title: "Nova Metálica",
        popupContent: "Fábrica",
        slug: "nova-metalica",
        siteType: "Institucional",
        imageCompanyUrl: LogoNovaMetalica,
        companyName: "Nova Metálica",
        tecnologias: ["react", "vite", "sass", "javascript"],
        data: "19/06/2025",
        description: "Apresentamos uma fábrica de steel frame e drywall, com foco em passar o valor por meio da construção sustentável.",
        urlPage: "https://novametalica.com.br",
        githubUrl: "https://github.com/alephsramos-dev",
        onDetails: "",
        popupBg: "#ffffff",
        popupBorder: "#00000010",
        popupColor: "#000000",
        siteBg: "#ffffff",
        siteBorder: "#00000010",
        siteColor: "#000000",
    },
    {
        image: "",
        title: "K'dea Construtora",
        slug: "kdea-construtora",
        popupContent: "Em alta",
        siteType: "Landing Page",
        imageCompanyUrl: LogoKdea,
        companyName: "K'dea Construtora",
        tecnologias: ["javascript", "html", "css"],
        data: "22/01/2025",
        description: "Um site de altissimo padrão, apresentando todas as obras feitas pela construtora de forma profissional e dinamica.",
        urlPage: "https://kdea.com.br",
        githubUrl: "https://github.com/alephsramos-dev",
        onDetails: "",
        popupBg: "#ffffff",
        popupBorder: "#00000010",
        popupColor: "#000000",
        siteBg: "#ffffff",
        siteBorder: "#00000010",
        siteColor: "#000000",
    },
    {
        image: "",
        title: "Cháles para Airbnb",
        popupContent: "Em alta",
        slug: "chales-para-airbnb",
        siteType: "Landing Page",
        imageCompanyUrl: LogoFastHomes,
        companyName: "Fast Homes",
        tecnologias: ["react", "vite", "n8n", "sass", "javascript"],
        data: "23/09/2025",
        description: "Uma página focada em vender chalés, apresentando de forma estratégica o uso em locação no airbnb.",
        urlPage: "https://chale.fasthomes.com.br",
        githubUrl: "https://github.com/alephsramos-dev",
        onDetails: "",
        popupBg: "#ffffff",
        popupBorder: "#00000010",
        popupColor: "#000000",
        siteBg: "#ffffff",
        siteBorder: "#00000010",
        siteColor: "#000000",
    },
    {
        image: "",
        title: "Pisos Vinilicos",
        popupContent: "Auge",
        slug: "pisos-vinilicos",
        siteType: "Landing Page",
        imageCompanyUrl: LogoFastSistemasConstrutivos,
        companyName: "Fast Sistemas Construtivos",
        tecnologias: ["n8n", "javascript", "html", "css"],
        data: "20/11/2024",
        description: "Site com foco em apresentar de forma de alto padrão todas as casas pré fábricadas.",
        urlPage: "https://pisos.fastsistemasconstrutivos.com.br",
        githubUrl: "https://github.com/alephsramos-dev",
        onDetails: "",
        popupBg: "#ffffff",
        popupBorder: "#00000010",
        popupColor: "#000000",
        siteBg: "#ffffff",
        siteBorder: "#00000010",
        siteColor: "#000000",
    },
    {
        image: "",
        title: "Fast Homes",
        popupContent: "Tendência",
        siteType: "Institucional",
        slug: "fast-homes",
        imageCompanyUrl: LogoFastHomes,
        companyName: "Fast Homes",
        tecnologias: ["react", "n8n", "firebase", "vite", "sass", "javascript"],
        data: "24/04/2025",
        description: "Site com foco em apresentar de forma de alto padrão todas as casas pré fábricadas.",
        urlPage: "https://fasthomes.com.br",
        githubUrl: "https://github.com/alephsramos-dev",
        onDetails: "",
        popupBg: "#ffffff",
        popupBorder: "#00000010",
        popupColor: "#000000",
        siteBg: "#ffffff",
        siteBorder: "#00000010",
        siteColor: "#000000",
    },
   
];

export default projects;


// {
//     image: "",
//     title: "",
//     popupContent: "",
//     siteType: "",
//     imageCompanyUrl: "",
//     companyName: "",
//     tecnologias: [],
//     data: "",
//     description: "",
//     urlPage: "",
//     githubUrl: "",
//     onDetails: "",
//     popupBg: "",
//     popupBorder: "",
//     popupColor: "",
//     siteBg: "",
//     siteBorder: "",
//     siteColor: "",

// }, 